#!/usr/bin/python
# -*- coding: utf-8 -*-

import time
import sys

from Utilities import *
from Log import Log
from Database import Database
from TVShow import TVShow
from Progress import Progress

# TODO SOONER

# Remove anything in the index where the file no longer exists on disk.

# Rather than being dumb like most other programs, hold the list of files to remove in RAM. If the number changes by more than some threshold (5% is a good start), then it's likely the movie folder has been renamed or some other user-error. Give the user chance to back out without changes in that instance.


# TODO Indexer class


def main():

    data_root = '/mnt/media/Movies/'
    tv_root = '/mnt/media/TV/'

    db = Database(data_root)
    log = Log(data_root)
    progress = Progress(log)

    tv_show_list = []

    subdirs = get_subdirs(tv_root)
    subdir_count = len(subdirs)

    # Purely check for deletions needed
    checking = "-c" in sys.argv[1:]

    # Act upon those deletions
    deleting = "-d" in sys.argv[1:]

    log.status("%d subdirs found in tv directory" % subdir_count)

    if not checking:
        for subdir in subdirs:
            s = TVShow(subdir, log) # Load up info from folder name into list of TV shows

            if s.is_in_db(db) and s.is_up_to_date(db):
                s.read_from_db(db)

            else: # Haven't seen it before, or if we have, it's out of date
                # get fresh info
                s.read_from_disk()

                # and store it for next time
                s.update_db(db)

            tv_show_list.append(s)

            s.update_watched(db)

            progress.update_log(len(tv_show_list), len(subdirs))

    # Removing TV shows that don't exist on disk any more..

    missing_count = 0
    for row in db.get_show_directories(): # Check for missing files
        directory = row['directory']
        if not os.path.isdir(directory):
            log.warn("Directory was missing on disk: %s" % directory)
            if deleting:
                log.warn("DELETING from db")
                db.exec_sql("DELETE FROM tv_shows WHERE directory = ?", [directory])
                db.exec_sql("DELETE FROM tv_episodes WHERE directory = ?", [directory])
            missing_count += 1
    if deleting:
         pass
    elif missing_count > 0:
        print "%d TV shows had missing directories. Run the program again with the -d option to delete these" % missing_count
    elif missing_count == 0:
        print "No TV shows had missing directories"

    # Removing TV episodes that don't exist on disk any more..

    missing_count = 0
    for row in db.get_episode_filenames(): # Check for missing files
        filename = row['filename']
        if not os.path.isfile(filename):
            log.warn("File was missing on disk: %s" % filename)
            if deleting:
                log.warn("DELETING from db")
                db.exec_sql("DELETE FROM tv_episodes WHERE filename = ?", [filename])
            missing_count += 1
    if deleting:
         pass
    elif missing_count > 0:
        print "%d TV shows had missing episodes. Run the program again with the -d option to delete these" % missing_count
    elif missing_count == 0:
        print "No TV shows had missing episodes"

    


    progress.final_log()
    print

if __name__ == '__main__':
    main()
 
